language: node_js
node_js:
  - "9"
  - "node"

sudo: true

services:
  - docker

before_script:
  - $TRAVIS_BUILD_DIR/Run.sh
  - cd server; npm install; cd ..
  - npm i -g eslint

script:
  - $TRAVIS_BUILD_DIR/Lint.sh
  - cd server && npm test && cd ..

