language: node_js
node_js:
  - "9"
  - "node"

sudo: true

services:
  - docker

before_script:
  - sudo apt update -qq -y
  - sudo apt install -y tor
  - docker swarm init # We need to initialize the host as a swarm manager first
  - $TRAVIS_BUILD_DIR/Setup.sh
  - $TRAVIS_BUILD_DIR/Run.sh shell
  - cd server; npm install; cd ..
  - npm i -g eslint eslint-config-google

script:
  - $TRAVIS_BUILD_DIR/Lint.sh
  - cd server && npm test && cd ..

after_success:
  - $TRAVIS_BUILD_DIR/GenerateDocs.sh
