version: "3.0"

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: tdse_d3f4u1t_d4t4b4s3_for_hon3y_coll3ction
      POSTGRES_DB: postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-vol:
