version: "3.2"

networks:
  backend:

volumes:
  postgres-vol:
  spider-log-vol:

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: $TDSE_DB_PASSWORD
      POSTGRES_USER: $TDSE_DB_USER
      POSTGRES_DB: $TDSE_DB_NAME
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - database
          - db
          - postgres
    ports:
      - "5432:5432"
    pid: "host"

  server:
    image: robrunne/tdse-spider:1.0.0
    restart: always
    networks:
      backend:
    ports:
      - "9000-9100:9000-9100"
      - target: 9101
        published: 9101
        protocol: ws
        mode: host
    volumes:
      - spider-log-vol:/log
    pid: "host"

